server:
  port: 8070

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/api/students/**
          filters:
            - StripPrefix=2
        - id: teacher-service
          uri: lb://teacher-service
          predicates:
            - Path=/api/teachers/**
          filters:
            - StripPrefix=2
        - id: homework-service
          uri: lb://homework-service
          predicates:
            - Path=/api/homeworks/**
          filters:
            - StripPrefix=2

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always 